//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalCabinetLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakenSet
    {
        public int Id { get; set; }
        public int IdBook { get; set; }
        public int IdReader { get; set; }
        public string TitleBook { get; set; }
        public string Author { get; set; }
        public string NameReader { get; set; }
        public string SurnameReader { get; set; }
        public string DateIssue { get; set; }
        public string DateDelivery { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ReadersSet ReadersSet { get; set; }
    }
}
